### ISSUE TITLE
Official release ?

### ISSUE THREAD

**Issue by ewilly** [pp-r/zwiicms_ynh#8]
Hi pp-r,
do you plan to officially release these app ? is it just for personnal usage or having roadblock ?

**Comment by pp-r** [comment]
Hi ewilly,

It's an app that i've tried to package with help from @kay0u and i just keep updating to the new version when i have some time. So it's not an official release but it could be one.

For that i would need time to switch to package v2 first (https://github.com/YunoHost/example_ynh).
Then searching how to upgrade the version number which is displayed in the web admin because when the app is already installed you can directly update it from its own web panel ... but i'm not a fluent packager ... like is my English ;-)

Feel free to fork it and make it an official app :-)
It could be great because it's an easy-to-handle cms without database.

**Comment by ewilly** [comment]
hello,
c'est fait, y'a plus qu'à attendre la publication dans le catalogue :-)
[https://github.com/YunoHost-Apps/zwiicms_ynh](https://github.com/YunoHost-Apps/zwiicms_ynh)

**Comment by pp-r** [comment]
Salut,

Merci pour le temps passé afin de porter cette application dans l'écosystème YunoHost !
Une fois publiée dans le catalogue je fermerai ce sujet.
Encore merci !
